### ISSUE TITLE
Getting 'System.IO.FileNotFoundException: Could not load file or assembly 'SharpSvn' The system cannot find the file specified' on docker container

### ISSUE THREAD

**Issue by StuSten** [AmpScm/SharpSvn#88]
Hi Im building a docker container using ubi8/dotnet-70-runtime with SharpSvn and im getting the following stack trace:

fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.IO.FileNotFoundException: Could not load file or assembly 'SharpSvn, Version=1.14001.156.0, Culture=neutral, PublicKeyToken=d729672594885a28'. The system cannot find the file specified.
      File name: 'SharpSvn, Version=1.14001.156.0, Culture=neutral, PublicKeyToken=d729672594885a28'
         at rundeck_supporting_services.Controllers.SVNController.SVNLookupByPath(String server, String path, String protocol, String port, Boolean showFiles, Int32 limit)
         at lambda_method1(Closure, Object, Object[])
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
      --- End of stack trace from previous location ---

**Comment by StuSten** [comment]
Just some further detail, the image im using is ubi8/dotnet-70-runtime and im using the 64 bit dll but I tried 32 bit and had the same issue.

**Comment by StuSten** [comment]
Thanks. It was the linux container being unsupported is the issue.
